one: one.cpp
	g++ -o out one.cpp -Wall -ansi -pedantic -O0 -g

two: two.cpp
	g++ -o out two.cpp -Wall -ansi -pedantic -O0 -g

three: three.cpp
	g++ -o out three.cpp -Wall -ansi -pedantic -O0 -g

four: four.cpp four.h
	g++ -o out four.cpp -Wall -ansi -pedantic -O0 -g
